import { mainResume } from "../../main_resume";
import type { ResumeDocument } from "../../types";

/** Tailored from https://www.linkedin.com/jobs/view/4466103929 — https://www.linkedin.com/jobs/view/4466103929 */
export const job4466103929Resume: ResumeDocument = {
  ...mainResume,
  id: "job-4466103929",
  tags: ["Full-Stack"],
  sourceUrl: "https://www.linkedin.com/jobs/view/4466103929",
  searchUrl: "https://www.linkedin.com/jobs/search-results/?currentJobId=4466103929&keywords=react&origin=JOB_SEARCH_PAGE_JOB_FILTER&referralSearchId=BNqbj0mU9FCWUFQo8Wf0sQ%3D%3D&f_EA=true",
  backgroundParagraphs: [
    "Senior Full-Stack Software Engineer in Lehi, UT. B.S. Computer Science, Stevens-Henager College. Builds production software in Next.js, Node.js, React, MySQL, PostgreSQL, GCP, and Docker, with a bias toward performance, reliability, and scalability.",
    "At Carketa and Encore Solar, shipped Next.js, Node.js, React, MySQL, PostgreSQL, GCP, and Docker web applications, APIs, and data pipelines — cut dashboard query time 75%; cut wait times 25%.",
  ],
  workExperience: [
    {
      company: "Carketa",
      location: {
        city: "Lehi",
        state: "UT",
        postalCode: "84043",
        country: "United States",
      },
      from: new Date(2022, 8, 1),
      to: new Date(),
      skills: [
        "Next.js",
        "React",
        "PostgreSQL",
        "GCP",
        "Docker",
        "Kubernetes",
        "CI/CD",
        "TypeScript",
        "DevOps",
        "Tailwind",
        "ArgoCD",
        "Claude",
        "Cursor",
        "BigQuery",
        "Cloud Storage",
      ],
      bulletpoints: [
        "Led a legacy PHP → full-stack Node.js/React (Next.js) migration; modernized core workflows and improved maintainability.",
        "Built a daily BigQuery + PostgreSQL pipeline (partitioning, materialized views, indexes) that cut dashboard query time 75% as vehicle volume grew.",
        "Designed a vehicle reconditioning web application (tasks, photos, real-time seller API sync) adopted by 10 new dealerships per month.",
      ],
    },
    {
      company: "Encore Solar",
      location: {
        city: "Lehi",
        state: "UT",
        postalCode: "84043",
        country: "United States",
      },
      from: new Date(2017, 11, 1),
      to: new Date(2022, 8, 1),
      skills: [
        "Next.js",
        "React",
        "PostgreSQL",
        "GCP",
        "Docker",
        "Kubernetes",
        "CI/CD",
        "TypeScript",
        "DevOps",
      ],
      bulletpoints: [
        "Led PHP → full-stack Node.js/React (Next.js) rewrite of a solar appraisal web application; hundreds of companies signed up to manage and sell installation contracts.",
        "Replaced polling support with a Node.js/Redis queue; cut wait times 25% with zero downtime.",
        "Shipped a custom solar proposal tool that raised revenue 10%.",
      ],
    },
    {
      company: "Grow",
      location: {
        city: "Orem",
        state: "UT",
        postalCode: "84057",
        country: "United States",
      },
      from: new Date(2014, 7, 10),
      to: new Date(2017, 11, 1),
      skills: [
        "Next.js",
        "Node.js",
        "React",
        "PostgreSQL",
        "Docker",
        "TypeScript",
        "Angular",
        "Tailwind",
        "Oracle",
        "Java",
        "Express",
        "Redis",
      ],
      bulletpoints: [
        "Served it from Node.js/Express with Oracle, PostgreSQL, and Redis; UI in Angular and full-stack React — cut report refresh time 50%.",
        "Built a B2B KPI dashboard for SMBs.",
        "Wired in hundreds of backend API data sources.",
      ],
    },
    {
      company: "Zagg",
      location: {
        city: "Salt Lake City",
        state: "UT",
        postalCode: "84101",
        country: "United States",
      },
      from: new Date(2009, 9, 5),
      to: new Date(2014, 7, 10),
      skills: [
        "Next.js",
        "MySQL",
        "PHP",
        "CodeIgniter",
        "jQuery",
        "CSS",
        "HTML",
      ],
      bulletpoints: [
        "Modeled MySQL data for orders, stock, and financial records.",
        "Built a custom PHP/CodeIgniter backend for shipping, finance, inventory, and custom orders.",
        "Shipped the store-ops UI in JavaScript, jQuery, CSS, and HTML; cut order-processing time 30%.",
      ],
    }
  ],
};
