import type { ResumeDocument } from "./types";

export const mainResume: ResumeDocument = {
  id: "main",
  tags: ["Software Engineer", "Full-Stack"],
  name: "Andrew Bliss",
  email: "andrewgbliss@gmail.com",
  phone: "+1 801 440 5615",
  tagline: "Senior Full-Stack Software Engineer",
  backgroundParagraphs: [
    "Senior full-stack engineer with a B.S. in Computer Science and 15+ years delivering web products for startups and established companies. Leads end-to-end work across legacy rewrites, customer-facing platforms, APIs, and the data systems that keep them fast in production. Track record includes shipping a proposal tool that raised revenue 10% while platforms scaled with customer growth.",
  ],
  address: {
    city: "Lehi",
    state: "UT",
    postalCode: "84043",
    country: "United States",
  },
  education: {
    school: "Stevens-Henager College",
    from: new Date(2002, 8, 1),
    to: new Date(2006, 9, 1),
    name: "Bachelor of Computer Science",
  },
  workExperience: [
    {
      company: "Carketa",
      location: {
        city: "Lehi",
        state: "UT",
        postalCode: "84043",
        country: "United States",
      },
      from: new Date(2022, 8, 1),
      to: new Date(),
      skills: [
        "React",
        "TypeScript",
        "Tailwind",
        "Next.js",
        "PostgreSQL",
        "Python",
        "Go",
        "Docker",
        "Kubernetes",
        "GCP",
        "ArgoCD",
        "Claude",
        "Cursor",
        "BigQuery",
        "Cloud Storage",
        "CI/CD",
        "DevOps",
        "Canvas",
        "WebGL",
      ],
      bulletpoints: [
        "Designed and shipped a Next.js vehicle reconditioning platform (tasking, photo capture, real-time seller API sync) that new dealerships adopt at a rate of 10 per month.",
        "Built a daily BigQuery and PostgreSQL analytics pipeline with partitioning, materialized views, and indexing that cut dashboard query time 75% as vehicle volume scaled.",
        "Led the migration of core product workflows from legacy PHP to React/Next.js, reducing technical debt and speeding delivery of dealership features.",
      ],
    },
    {
      company: "Encore Solar",
      location: {
        city: "Lehi",
        state: "UT",
        postalCode: "84043",
        country: "United States",
      },
      from: new Date(2017, 11, 1),
      to: new Date(2022, 8, 1),
      skills: [
        "React",
        "TypeScript",
        "Next.js",
        "PostgreSQL",
        "Python",
        "Docker",
        "Kubernetes",
        "GCP",
        "CI/CD",
        "DevOps",
      ],
      bulletpoints: [
        "Shipped a Next.js solar proposal tool that increased sales revenue 10% by shortening the path from design to signed contract.",
        "Replaced polling-based support with a Node.js/Redis queue architecture, cutting customer wait times 25% with zero downtime during the cutover.",
        "Led a PHP-to-React/Next.js rewrite of the solar appraisal platform, enabling hundreds of companies to manage and sell installation contracts on a modern stack.",
      ],
    },
    {
      company: "Grow",
      location: {
        city: "Orem",
        state: "UT",
        postalCode: "84057",
        country: "United States",
      },
      from: new Date(2014, 7, 10),
      to: new Date(2017, 11, 1),
      skills: [
        "React",
        "TypeScript",
        "Angular",
        "Tailwind",
        "Next.js",
        "PostgreSQL",
        "Oracle",
        "Java",
        "Node.js",
        "Express",
        "Redis",
        "Docker",
      ],
      bulletpoints: [
        "Built a React B2B KPI dashboard that gave SMBs a single view of performance across their operations.",
        "Integrated hundreds of backend API data sources so customers could trust one reporting surface instead of fragmented tools.",
        "Delivered the product on Node/Express with Oracle, PostgreSQL, and Redis, and an Angular/React UI that cut report refresh time 50%.",
      ],
    },
    {
      company: "Zagg",
      location: {
        city: "Salt Lake City",
        state: "UT",
        postalCode: "84101",
        country: "United States",
      },
      from: new Date(2010, 11, 1),
      to: new Date(2014, 7, 10),
      skills: ["PHP", "MySQL", "jQuery"],
      bulletpoints: [
        "Built a PHP/CodeIgniter backend for shipping, finance, inventory, and custom orders that replaced fragmented store operations.",
        "Designed MySQL schemas for orders, stock, and financial records to support accurate fulfillment and reporting.",
        "Shipped the store-ops UI in JavaScript, jQuery, CSS, and HTML, cutting order-processing time 30% for warehouse and support teams.",
      ],
    },
    {
      company: "Classtop",
      location: {
        city: "Draper",
        state: "UT",
        postalCode: "84020",
        country: "United States",
      },
      from: new Date(2009, 9, 5),
      to: new Date(2010, 11, 1),
      skills: ["C#", ".NET", "PHP", "MySQL", "jQuery"],
      bulletpoints: [
        "Built PHP and C# Facebook applications that let students connect around classroom specialties and complete courses online.",
        "Implemented MySQL sharding and replication to keep data retrieval fast as the product grew, cutting query latency 75%.",
        "Hardened performance and data access as the application scaled to 100,000 users without sacrificing uptime.",
      ],
    },
    {
      company: "Stevens-Henager College",
      location: {
        city: "Salt Lake City",
        state: "UT",
        postalCode: "84101",
        country: "United States",
      },
      from: new Date(2002, 3, 2),
      to: new Date(2006, 9, 1),
      skills: [
        "ColdFusion",
        "Oracle",
        "SQL",
        "JavaScript",
        "CSS",
        "HTML",
        ".NET",
      ],
      bulletpoints: [
        "Built the ColdFusion application for student records, finances, schedules, and testing used daily by staff and administration.",
        "Modeled academic data in Oracle and optimized access paths, cutting record lookup time 40%.",
        "Delivered the staff UI in ColdFusion, JavaScript, CSS, and HTML so academic teams could manage records without manual workarounds.",
      ],
    },
  ],
  links: [
    "https://www.linkedin.com/in/andrewgbliss",
    "https://github.com/andrewgbliss",
    "https://www.andrewgbliss.com",
  ],
};
