import type { ResumeDocument } from "../job-listings/utils/types";

export const mainResume: ResumeDocument = {
  id: "main",
  tags: ["Software Engineer", "Full-Stack"],
  name: "Andrew Bliss",
  email: "andrewgbliss@gmail.com",
  phone: "+1 801 440 5615",
  tagline: "Senior Full-Stack Software Engineer",
  backgroundParagraphs: [
    "Senior Full-Stack Software Engineer with 15+ years of developing software for startups and established companies. Background in web development with a track record of building, shipping, and scaling products that deliver value. Strong problem solving skills and the ability to effectively communicate with clients and team members.",
  ],
  address: {
    city: "Lehi",
    state: "UT",
    postalCode: "84043",
    country: "United States",
  },
  education: {
    school: "Stevens-Henager College",
    from: new Date(2002, 8, 1),
    to: new Date(2006, 9, 1),
    name: "Bachelor of Computer Science",
  },
  workExperience: [
    {
      company: "Carketa",
      location: {
        city: "Lehi",
        state: "UT",
        postalCode: "84043",
        country: "United States",
      },
      from: new Date(2022, 8, 1),
      to: new Date(),
      skills: [
        "React",
        "TypeScript",
        "Tailwind",
        "Shadcn/ui",
        "Next.js",
        "PostgreSQL",
        "Python",
        "Go",
        "Docker",
        "Kubernetes",
        "GCP",
        "ArgoCD",
        "Claude",
        "Cursor",
        "BigQuery",
        "Cloud Storage",
        "CI/CD",
        "DevOps",
        "Canvas",
        "WebGL",
      ],
      bulletpoints: [
        "Designed and shipped a Next.js vehicle reconditioning platform (tasking, photo capture, real-time seller API sync) that allowed many new dealerships to start scaling their operations.",
        "Built a daily BigQuery and PostgreSQL analytics pipeline with partitioning, and indexing that cut dashboard query time 75% as vehicle volume scaled.",
        "Debugged and maintained product workflows from PHP, Python, and Go applications.",
      ],
    },
    {
      company: "Encore Solar",
      location: {
        city: "Lehi",
        state: "UT",
        postalCode: "84043",
        country: "United States",
      },
      from: new Date(2017, 11, 1),
      to: new Date(2022, 8, 1),
      skills: [
        "React",
        "TypeScript",
        "Next.js",
        "PostgreSQL",
        "Python",
        "Docker",
        "Kubernetes",
        "GCP",
        "CI/CD",
        "DevOps",
      ],
      bulletpoints: [
        "Shipped a Next.js solar proposal tool that increased sales revenue 10 fold for clients by shortening the path from design to signed contract.",
        "Built a customer service polling-based support system with a Node.js/Redis queue architecture, cutting customer wait times 25% with zero downtime during the cutover.",
        "Migrated data from MySQL to PostgreSQL, PHP to React/Next.js, and legacy code to modern best practices. Speeding up applications significantly as we started scaling up our users.",
      ],
    },
    {
      company: "Grow",
      location: {
        city: "Orem",
        state: "UT",
        postalCode: "84057",
        country: "United States",
      },
      from: new Date(2014, 7, 10),
      to: new Date(2017, 11, 1),
      skills: [
        "React",
        "TypeScript",
        "Angular",
        "Tailwind",
        "Next.js",
        "PostgreSQL",
        "Oracle",
        "Java",
        "Node.js",
        "Express",
        "Redis",
        "Docker",
      ],
      bulletpoints: [
        "Built a React B2B KPI dashboard that gave SMBs a view into their business performance and how to scale.",
        "Integrated hundreds of backend API data sources: Quickbooks, stripe, MySQL, Oracle, PostgreSQL and more.",
        "Built and maintained a Node/Express backend with PostgreSQL, Redis, and an Angular/React UI frontend dashboard.",
      ],
    },
    {
      company: "Zagg",
      location: {
        city: "Salt Lake City",
        state: "UT",
        postalCode: "84101",
        country: "United States",
      },
      from: new Date(2010, 11, 1),
      to: new Date(2014, 7, 10),
      skills: ["PHP", "MySQL", "jQuery", "CSS", "HTML", "JavaScript"],
      bulletpoints: [
        "Built a PHP/CodeIgniter backend for shipping, finance, inventory, and custom orders.",
        "Designed MySQL schemas for orders, inventory, and operations of the warehouse.",
        "Shipped many optimised SEO freindly front facing web pages in JavaScript, jQuery, CSS, and HTML.",
      ],
    },
    {
      company: "Classtop",
      location: {
        city: "Draper",
        state: "UT",
        postalCode: "84020",
        country: "United States",
      },
      from: new Date(2009, 9, 5),
      to: new Date(2010, 11, 1),
      skills: ["C#", ".NET", "PHP", "MySQL", "jQuery"],
      bulletpoints: [
        "Built PHP and C# Facebook applications that let students connect around classroom specialties and complete courses online.",
        "Implemented MySQL sharding and replication to keep data retrieval fast as the product grew, cutting query latency 75%.",
        "Hardened performance with indexes and query analysis as the application scaled to 100,000 users without sacrificing uptime.",
      ],
    },
    {
      company: "Stevens-Henager College",
      location: {
        city: "Salt Lake City",
        state: "UT",
        postalCode: "84101",
        country: "United States",
      },
      from: new Date(2002, 3, 2),
      to: new Date(2006, 9, 1),
      skills: [
        "ColdFusion",
        "Oracle",
        "SQL",
        "JavaScript",
        "CSS",
        "HTML",
        ".NET",
      ],
      bulletpoints: [
        "Built the ColdFusion application for student records, finances, schedules, and testing used daily by staff and administration.",
        "Maintained backend data in Oracle with optimizations to keep the application fast as the student body grew.",
        "Delivered the staff UI in ColdFusion, JavaScript, CSS, and HTML so academic teams could manage records efficiently.",
      ],
    },
  ],
  links: [
    "https://www.linkedin.com/in/andrewgbliss",
    "https://github.com/andrewgbliss",
    "https://www.andrewgbliss.com",
  ],
};
