import type { KeywordPack, KeywordSkill } from "./types";

function skill(
  name: string,
  aliases: Array<string>,
  pattern: RegExp,
): KeywordSkill {
  return { name, aliases, pattern };
}

/** Skills, phrases, and values the scraper looks for in web-developer listings. */
export const webDeveloperKeywords: KeywordPack = {
  id: "web-developer",
  skills: [
    skill("React", ["react", "reactjs", "react.js"], /\breact(?:\.js|js)?\b/i),
    skill(
      "Next.js",
      ["next.js", "nextjs", "next js"],
      /\bnext(?:\.js|js|\s+js)\b/i,
    ),
    skill("TypeScript", ["typescript", "ts"], /\btypescript\b/i),
    skill("JavaScript", ["javascript", "js"], /\bjavascript\b/i),
    skill("Node.js", ["node.js", "nodejs", "node"], /\bnode(?:\.?js)?\b/i),
    skill("Express", ["express", "express.js", "expressjs"], /\bexpress(?:\.?js)?\b/i),
    skill("Angular", ["angular", "angularjs"], /\bangular\b/i),
    skill("Vue", ["vue", "vue.js", "vuejs"], /\bvue(?:\.js|js)?\b/i),
    skill("HTML", ["html", "html5"], /\bhtml5?\b/i),
    skill("CSS", ["css", "css3"], /\bcss3?\b/i),
    skill("Tailwind", ["tailwind", "tailwindcss", "tailwind css"], /\btailwind\b/i),
    skill("Sass", ["sass", "scss"], /\b(?:sass|scss)\b/i),
    skill("jQuery", ["jquery"], /\bjquery\b/i),
    skill("GraphQL", ["graphql"], /\bgraphql\b/i),
    skill("REST", ["rest", "restful", "rest apis"], /\brest(?:ful)?(?:\s+apis?)?\b/i),
    skill("PostgreSQL", ["postgresql", "postgres", "psql"], /\bpostgres(?:ql)?\b/i),
    skill("MySQL", ["mysql"], /\bmysql\b/i),
    skill("MongoDB", ["mongodb", "mongo"], /\bmongo(?:db)?\b/i),
    skill("Redis", ["redis"], /\bredis\b/i),
    skill("Oracle", ["oracle"], /\boracle\b/i),
    skill("SQL", ["sql"], /\bsql\b/i),
    skill("BigQuery", ["bigquery"], /\bbigquery\b/i),
    skill("Docker", ["docker"], /\bdocker\b/i),
    skill("Kubernetes", ["kubernetes", "k8s"], /\bkubernetes\b|\bk8s\b/i),
    skill("CI/CD", ["ci/cd", "cicd"], /\bci\/cd\b|\bcicd\b/i),
    skill("DevOps", ["devops"], /\bdevops\b/i),
    skill("Git", ["git"], /\bgit\b/i),
    skill("GitHub", ["github"], /\bgithub\b/i),
    skill("AWS", ["aws", "amazon web services"], /\baws\b|amazon web services/i),
    skill("GCP", ["gcp", "google cloud"], /\bgcp\b|google cloud/i),
    skill("Azure", ["azure"], /\bazure\b/i),
    skill("Python", ["python"], /\bpython\b/i),
    skill("Go", ["go", "golang"], /\bgolang\b|(?<![\w.])go(?![.\w])/i),
    skill("Java", ["java"], /\bjava\b/i),
    skill("PHP", ["php"], /\bphp\b/i),
    skill("C#", ["c#", "csharp", "c-sharp", "c sharp"], /c#|c-sharp|\bcsharp\b|\bc sharp\b/i),
    skill(".NET", [".net", "dotnet", "asp.net"], /\.net\b|\bdotnet\b|\basp\.net\b/i),
    skill("Ruby", ["ruby", "rails", "ruby on rails"], /\bruby\b|\brails\b/i),
    skill("Webpack", ["webpack"], /\bwebpack\b/i),
    skill("Vite", ["vite"], /\bvite\b/i),
    skill("Linux", ["linux"], /\blinux\b/i),
    skill("Terraform", ["terraform"], /\bterraform\b/i),
    skill("ArgoCD", ["argocd", "argo cd"], /\bargo\s?cd\b/i),
    skill("Cloud Storage", ["cloud storage", "gcs"], /\bcloud storage\b|\bgcs\b/i),
    skill("CodeIgniter", ["codeigniter"], /\bcodeigniter\b/i),
    skill("ColdFusion", ["coldfusion"], /\bcoldfusion\b/i),
    skill("Canvas", ["canvas"], /\bcanvas\b/i),
    skill("WebGL", ["webgl"], /\bwebgl\b/i),
    skill("Claude", ["claude"], /\bclaude\b/i),
    skill("Cursor", ["cursor"], /\bcursor\b/i),
  ],
  phrases: [
    { phrase: "full-stack", pattern: /\bfull[-\s]?stack\b/i },
    { phrase: "REST APIs", pattern: /\brest(?:ful)?(?:\s+apis?)?\b/i },
    { phrase: "web application", pattern: /\bweb apps?\b|\bweb applications?\b/i },
    { phrase: "front-end", pattern: /\bfront[-\s]?end\b/i },
    { phrase: "back-end", pattern: /\bback[-\s]?end\b/i },
    { phrase: "microservices", pattern: /\bmicroservices?\b/i },
    { phrase: "production", pattern: /\bproduction\b/i },
    { phrase: "CI/CD", pattern: /\bci\/cd\b/i },
  ],
  values: [
    "performance",
    "reliability",
    "scalability",
    "security",
    "maintainability",
    "quality",
  ],
};
